#! python3
# basketPriceRecommendations.py - Suggest the amount of a stock to buy or sell,
# based on preset units within a basket.

import numpy as np
import os
import pandas as pd
import time
import yfinance as yf

file_path = '.\\Reference\\%s'
file_name = 'stocks.csv'

sleep = 0.26

inv_approx_value = 23.5
ira_approx_value = 92.5
clt_approx_value = 160

# Move from thousands back to single dollars.
factor = 1000
inv_approx_value *= factor
ira_approx_value *= factor
clt_approx_value *= factor

# Break into 30 units.
inv_unit = inv_approx_value / 30
ira_unit = ira_approx_value / 30
clt_unit = clt_approx_value / 30

df = pd.read_csv(os.path.abspath(file_path %
                                 file_name)).sort_values(by = 'TICKER')

# Select only relevant columns.
df = df[['TICKER', 'INVEST_BUY', 'INVEST_SELL', 'IRA_BUY', 'IRA_SELL',
         'CLT_BUY', 'CLT_SELL']].copy()

# Exclude any with null values.
df = df[~df[['INVEST_BUY', 'INVEST_SELL',
             'IRA_BUY', 'IRA_SELL',
             'CLT_BUY', 'CLT_SELL']].isna().all(axis = 1)].copy()

# Align buy and sell units more or less to the amount generated by sells.
inv_buy_unit = inv_unit * 0.0067
ira_buy_unit = ira_unit * 0.1667
clt_buy_unit = clt_unit * 1.0

print('Inv buy unit: %s' % inv_buy_unit)
print('Ira buy unit: %s' % ira_buy_unit)
print('Clt buy unit: %s' % clt_buy_unit)

# Note that inv sell unit has to be brought down close to $1.
inv_sell_unit = inv_unit / 30
ira_sell_unit = ira_unit * 1.0
clt_sell_unit = clt_unit * 1.0

def print_recommendations(df, recommendation, account,
                          account_action, shares_recommendation):
    
    print('\n%s the following for the %s account:\n' % (recommendation,
                                                        account))
    
    for n in range(len(df)):
        row = df.loc[n, :]
        
        if not np.isnan(row[account_action]):
            print('%s:' % (row['TICKER']),
                  '{:.3f}'.format(row[shares_recommendation]), 'shares at',
                  '${:.2f}.'.format(row['PRICE']))

    return

def recommend_amount(row):

    # Be respectful to the server.
    time.sleep(sleep)    

    try:
        
        print('Getting the prices and amounts for %s.' % row['TICKER'])

        # Get the closing price.
        price = yf.Ticker(row['TICKER']).history().iloc[-1]['Close']
        
        inv_buy_share = shares_amount(inv_buy_unit, row['INVEST_BUY'], price)
        ira_buy_share = shares_amount(ira_buy_unit, row['IRA_BUY'], price)
        clt_buy_share = shares_amount(clt_buy_unit, row['CLT_BUY'], price)
        
        inv_sell_share = shares_amount(inv_sell_unit, row['INVEST_SELL'],
                                          price)
        ira_sell_share = shares_amount(ira_sell_unit, row['IRA_SELL'],
                                       price)
        clt_sell_share = shares_amount(clt_sell_unit, row['CLT_SELL'],
                                       price)
            
        return {'TICKER' : row['TICKER'],
                'PRICE' : price,
                'INVEST_BUY_SHARES' : inv_buy_share,
                'IRA_BUY_SHARES' : ira_buy_share,
                'CLT_BUY_SHARES' : clt_buy_share,
                'INVEST_SELL_SHARES' : inv_sell_share,
                'IRA_SELL_SHARES' : ira_sell_share,
                'CLT_SELL_SHARES' : clt_sell_share}
    
    except IndexError as e:
        print('Error encountered on %s: %s' % (row['TICKER'], e))
        
        return {'TICKER' : row['TICKER'],
                'PRICE' : np.nan,
                'INVEST_BUY_SHARES' : np.nan,
                'IRA_BUY_SHARES' : np.nan,
                'INVEST_SELL_SHARES' : np.nan,
                'IRA_SELL_SHARES' : np.nan}

# Returns the amount of shares to buy or sell.
def shares_amount(units, basket_size, price):
    return units / basket_size / price if basket_size is not np.nan\
        else basket_size

df = pd.merge(df, pd.DataFrame(list(df.apply(recommend_amount, axis = 1))),
              on = 'TICKER')

print_recommendations(df, 'BUY', 'INVESTMENT',
                      'INVEST_BUY', 'INVEST_BUY_SHARES')

print_recommendations(df, 'BUY', 'IRA',
                      'IRA_BUY', 'IRA_BUY_SHARES')

print_recommendations(df, 'BUY', 'CLT',
                      'CLT_BUY', 'CLT_BUY_SHARES')

print_recommendations(df, 'SELL', 'INVESTMENT',
                      'INVEST_SELL', 'INVEST_SELL_SHARES')

print_recommendations(df, 'SELL', 'IRA',
                      'IRA_SELL', 'IRA_SELL_SHARES')

print_recommendations(df, 'SELL', 'CLT',
                      'CLT_SELL', 'CLT_SELL_SHARES')
